FROM nginx:latest 
COPY nginx.conf /etc/nginx/nginx.conf 

Nginx.conf: 

events {} 
http { 
    server { 
        listen 80; 
        location / { 
            proxy_pass http://flask-app:5500; 
        } 
    } 
} 
